### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ppmaster69** [crazymoose77756/SteveHClient#1]
running this mod together with inertia client it will crash you 100% at the time if you get kicked to auto reconnect screen i havent 
tried running it without it to see if the same happens

**Comment by crazymoose77756** [comment]
This would only happen when running both clients at once, I believe you have have conflicting settings on each that would cause the crash on the reconnect screen. Could you provide your crash log? As I was unable to recreate this

**Comment by ppmaster69** [comment]
[crash-2021-02-21_15.54.19-client.txt](https://github.com/crazymoose77756/SteveHClient/files/6018013/crash-2021-02-21_15.54.19-client.txt)

**Comment by ppmaster69** [comment]
also i just tested it was inertia ill try a never version of inertia

**Comment by crazymoose77756** [comment]
Thanks for letting me know and thanks for testing it out. Any features you want to be added?

**Comment by ppmaster69** [comment]
well meteor has a bug that you go in f5 mode your screen goes black no idea what causes it would be cool to get patched

**Comment by crazymoose77756** [comment]
Gotcha, I am going to close this, but feel free to open another if something else happens

**Comment by crazymoose77756** [comment]
Wait, when you go into f5 with SteveHClient, does your screen go black @ppmaster69

**Comment by ppmaster69** [comment]
yes

**Comment by ppmaster69** [comment]
also what servers you play on @crazymoose77756

**Comment by crazymoose77756** [comment]
huh mine doesn't, are you using the latest version? Maybe others mods affect it. I can test it out later. PM me

**Comment by ppmaster69** [comment]
ok ill try with out other mods

**Comment by ppmaster69** [comment]
just steve client works ill look into which mod causes it

**Comment by crazymoose77756** [comment]
Ok thanks for testing this out. Feel free to make a pull request if you want to improve tracers, or if you have suggestions!
