### ISSUE TITLE
not a bug but idk how to make a suggestion so i just make here 

### ISSUE THREAD

**Issue by ppmaster69** [crazymoose77756/SteveHClient#2]
would be cool of certain bits of the client Hud could be disabled such as 
hahahah imagine this being on your screen <player>
or lieke the mini player and stuff like that
or people on your friend list appearing in different colour on tab menu
and .friend remove <all>

**Comment by crazymoose77756** [comment]
Ah ok, You can remove the stuff from the hud, just go into the module settings and click on "editor" and then right click on the stuff you don't want. I will check about friend remove (might be a thing already). Definitely friend color tab! Would you like to pre test future releases when they are drafted?

**Comment by ppmaster69** [comment]
yes sure

**Comment by ppmaster69** [comment]
also can i have your discord?

**Comment by crazymoose77756** [comment]
crazymoose77756#8319
